spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exercise_9
    username: root
    password: Raptor.221
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl_auto: create-drop